#markdown: rdiscount
permalink: /:title/
url: http://wenle.github.io
#highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate]
paginate: 100
paginate_path: "page:num"
name: Wenle
#description:
author: Wenle
email: baowenle@outlook.com
duoshuo: wenleplus
weibo: nbug
hub: wenle 
safe: false
about: "工程师"
